#!/usr/bin/env python3
"""
Extract Silero VAD v4 weights from ONNX model and generate weights.h
for the C→WASM inference engine.

Usage:
    python extract_weights.py path/to/silero_vad.onnx -o src/weights.h

Requires: onnx, numpy
  pip install onnx numpy
"""

import argparse
import struct
import sys
from pathlib import Path

import numpy as np
import onnx

MODEL_DIMENSIONS = {
    "conv_in_ch": 1,
    "conv_out_ch": 64,
    "conv_kernel": 256,
    "conv_stride": 160,
    "gru_input_size": 64,
    "gru_hidden_size": 64,
}

HEADER_TEMPLATE = """\
/*
 * weights.h — Silero VAD model weights (auto-generated by extract_weights.py)
 * DO NOT EDIT — generated from {source}
 * Generated on {date}
 */

#ifndef SILERO_VAD_WEIGHTS_H
#define SILERO_VAD_WEIGHTS_H

/*
 * Model architecture:
 *   Conv1D(1, 64, kernel=256, stride=160)
 *   GRU(64, 64, 1)
 *   FC(64, 1) + Sigmoid
 */

/* --- Conv1D weight & bias --- */
/* shape: [{conv_out_ch}, {conv_in_ch}, {conv_kernel}] = {conv_weight_size} floats */
static const float weights_conv_weight[{conv_weight_size}] = {{
{conv_weight_data}
}};

/* shape: [{conv_out_ch}] = {conv_bias_size} floats */
static const float weights_conv_bias[{conv_bias_size}] = {{
{conv_bias_data}
}};

/* --- GRU weights --- */
/* GRU has 3 gates (reset, update, new), each with input and hidden projections */
/* shape: [3 * {gru_hidden}, {gru_input}] = {gru_w_ih_size} floats */
static const float weights_gru_w_ih[{gru_w_ih_size}] = {{
{gru_w_ih_data}
}};

/* shape: [3 * {gru_hidden}, {gru_hidden}] = {gru_w_hh_size} floats */
static const float weights_gru_w_hh[{gru_w_hh_size}] = {{
{gru_w_hh_data}
}};

/* shape: [3 * {gru_hidden}] = {gru_b_ih_size} floats */
static const float weights_gru_b_ih[{gru_b_ih_size}] = {{
{gru_b_ih_data}
}};

/* shape: [3 * {gru_hidden}] = {gru_b_hh_size} floats */
static const float weights_gru_b_hh[{gru_b_hh_size}] = {{
{gru_b_hh_data}
}};

/* --- Fully connected weight & bias --- */
/* shape: [1, {gru_hidden}] = {fc_weight_size} floats */
static const float weights_fc_weight[{fc_weight_size}] = {{
{fc_weight_data}
}};

/* shape: [1] = {fc_bias_size} floats */
static const float weights_fc_bias[{fc_bias_size}] = {{
{fc_bias_data}
}};

#endif /* SILERO_VAD_WEIGHTS_H */
"""


def format_array(arr: np.ndarray, indent: int = 2) -> str:
    """Format a numpy array as a C float array initializer."""
    flat = arr.flatten()
    lines = []
    prefix = " " * indent
    line = prefix
    for i, val in enumerate(flat):
        s = f"{val:.8f}f, "
        if len(line + s) > 78:
            lines.append(line.rstrip())
            line = prefix + s
        else:
            line += s
    if line.strip():
        lines.append(line.rstrip())
    return "\n".join(lines)


def extract_weights(model_path: str) -> dict[str, np.ndarray]:
    """Extract weight tensors from ONNX model."""
    model = onnx.load(model_path)
    weights = {}

    # Graph inputs to identify tensors
    graph = model.graph

    # Initializers contain the weight tensors
    for init in graph.initializer:
        name = init.name
        # Convert to numpy
        tensor = onnx.numpy_helper.to_array(init)
        weights[name] = tensor
        print(f"  Found tensor: {name} shape={tensor.shape}", file=sys.stderr)

    # Map ONNX weight names to our expected names
    # Silero VAD v4 ONNX naming convention (varies by model export):
    name_map = {}
    for name in weights:
        name_lower = name.lower()

        # Conv1D
        if "conv" in name_lower and "weight" in name_lower:
            name_map["conv_weight"] = name
        elif "conv" in name_lower and "bias" in name_lower:
            name_map["conv_bias"] = name

        # GRU
        elif "gru" in name_lower or "rnn" in name_lower:
            if "weight_ih" in name_lower or "weight_ih_l0" in name_lower:
                name_map["gru_w_ih"] = name
            elif "weight_hh" in name_lower or "weight_hh_l0" in name_lower:
                name_map["gru_w_hh"] = name
            elif "bias_ih" in name_lower or "bias_ih_l0" in name_lower:
                name_map["gru_b_ih"] = name
            elif "bias_hh" in name_lower or "bias_hh_l0" in name_lower:
                name_map["gru_b_hh"] = name

        # FC (Linear)
        elif "fc" in name_lower or "linear" in name_lower or "classifier" in name_lower:
            if "weight" in name_lower:
                name_map["fc_weight"] = name
            elif "bias" in name_lower:
                name_map["fc_bias"] = name

        # Last resort: look at shapes
        elif fnl := name_lower.split(".")[-1]:
            if fnl == "weight" and "conv_weight" not in name_map:
                if len(tensor.shape) >= 2:
                    name_map["conv_weight"] = name
            elif fnl == "bias" and "conv_bias" not in name_map:
                if len(tensor.shape) == 1:
                    name_map["conv_bias"] = name

    print(f"\n  Mapped names: {name_map}", file=sys.stderr)

    result = {}
    for key, onnx_name in name_map.items():
        result[key] = weights[onnx_name]
        print(f"  {key}: {onnx_name} shape={weights[onnx_name].shape}", file=sys.stderr)

    return result


def generate_header(weights: dict[str, np.ndarray], source: str) -> str:
    """Generate the C header file content."""
    # Validate expected keys
    expected = ["conv_weight", "conv_bias", "gru_w_ih", "gru_w_hh",
                 "gru_b_ih", "gru_b_hh", "fc_weight", "fc_bias"]
    for key in expected:
        if key not in weights:
            print(f"  WARNING: missing weight '{key}'", file=sys.stderr)

    from datetime import datetime

    fmt_data = {
        "source": source,
        "date": datetime.now().isoformat(),
        "conv_out_ch": MODEL_DIMENSIONS["conv_out_ch"],
        "conv_in_ch": MODEL_DIMENSIONS["conv_in_ch"],
        "conv_kernel": MODEL_DIMENSIONS["conv_kernel"],
        "gru_input": MODEL_DIMENSIONS["gru_input_size"],
        "gru_hidden": MODEL_DIMENSIONS["gru_hidden_size"],
    }

    # Format each weight array
    for key in expected:
        if key in weights:
            arr = weights[key]
            fmt_data[f"{key}_data"] = format_array(arr)
            fmt_data[f"{key}_size"] = arr.size
        else:
            fmt_data[f"{key}_data"] = "    /* MISSING */"
            fmt_data[f"{key}_size"] = 0

    return HEADER_TEMPLATE.format(**fmt_data)


def main():
    parser = argparse.ArgumentParser(description="Extract Silero VAD weights from ONNX")
    parser.add_argument("onnx_path", help="Path to silero_vad.onnx")
    parser.add_argument("-o", "--output", default="src/weights.h",
                        help="Output C header path")
    args = parser.parse_args()

    model_path = Path(args.onnx_path)
    if not model_path.exists():
        print(f"Error: {model_path} not found", file=sys.stderr)
        sys.exit(1)

    print("Extracting weights from ONNX model...", file=sys.stderr)
    weights = extract_weights(str(model_path))

    print(f"Generating {args.output}...", file=sys.stderr)
    header = generate_header(weights, model_path.name)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header)

    total_params = sum(w.size for w in weights.values())
    print(f"Done! {len(weights)} tensors, {total_params} parameters", file=sys.stderr)
    print(f"Output: {output_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
