/*
 * silero_vad.h — Silero VAD v4 C header.
 *
 * Architecture (small model):
 *   Input:  512 samples @ 16kHz (32ms window)
 *   Conv1D: 1→64, kernel=256, stride=160
 *   GRU:    64→64, 1 layer
 *   FC:     64→1 + Sigmoid
 *   Output: speech probability [0, 1]
 *
 * This file is compiled with emcc to produce silero_vad.wasm.
 * Model weights are embedded via weights.h (generated by extract_weights.py).
 */

#ifndef SILERO_VAD_H
#define SILERO_VAD_H

/* Initialize VAD with model weights and sample rate.
 * model_ptr: pointer to serialized weights in WASM heap (0 if embedded).
 * sample_rate: must be 48000 (internally downsampled to 16000). */
void vad_init(int model_ptr, int sample_rate);

/* Process 512 PCM samples (48kHz) and return speech probability.
 * input_ptr: pointer to 512 float32 samples in WASM heap.
 * samples: number of valid samples (≤512, rest zero-padded).
 * Returns probability in [0, 1]. */
float vad_process(int input_ptr, int samples);

/* Reset internal GRU hidden state. */
void vad_reset(void);

#endif /* SILERO_VAD_H */
