/*
 * silero_vad.c — Silero VAD v4 inference implementation (C→WASM).
 *
 * Weights header generated by extract_weights.py from the ONNX model.
 * If weights.h is not available, #define VAD_NO_WEIGHTS and weights
 * can be loaded at runtime via vad_init(model_ptr).
 *
 * Compile:
 *   emcc -O3 -msimd128 -s WASM=1 -s INITIAL_MEMORY=8MB \
 *        -s EXPORTED_FUNCTIONS='["_vad_init","_vad_process","_vad_reset"]' \
 *        -o dist/silero_vad.js src/silero_vad.c
 */

#include <math.h>
#include <stdint.h>
#include <string.h>

/* ------------------------------------------------------------------ */
/* Model dimensions */
#define VAD_SAMPLE_RATE_16K 16000
#define VAD_SAMPLE_RATE_48K 48000
#define VAD_FRAME_SIZE 512        /* samples @ 16kHz = 32ms */
#define VAD_INPUT_48K_SIZE 1536   /* samples @ 48kHz = 32ms (3x decimation) */

#define CONV_IN_CH 1
#define CONV_OUT_CH 64
#define CONV_KERNEL 256
#define CONV_STRIDE 160

#define GRU_INPUT_SIZE 64
#define GRU_HIDDEN_SIZE 64

/* ------------------------------------------------------------------ */
/* Include embedded weights (generated) */
#if __has_include("weights.h")
#include "weights.h"
#else
/* Fallback: weights loaded at runtime */
#define VAD_LOAD_WEIGHTS_AT_RUNTIME
#endif

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ------------------------------------------------------------------ */
/* Internal state */
static float hidden_state[GRU_HIDDEN_SIZE];
static int sr = VAD_SAMPLE_RATE_48K;

/* Pointers to weights (either static or heap) */
static const float *conv_weight;  /* [64][1][256] row-major */
static const float *conv_bias;    /* [64] */
static const float *gru_w_ih;     /* [192][64] (3 gates x 64 x 64) */
static const float *gru_w_hh;     /* [192][64] */
static const float *gru_b_ih;     /* [192] */
static const float *gru_b_hh;     /* [192] */
static const float *fc_weight;    /* [1][64] */
static const float *fc_bias;      /* [1] */

/* ------------------------------------------------------------------ */
/* Math helpers */

static float sigmoid(float x) {
    return 1.0f / (1.0f + expf(-x));
}

static float relu(float x) {
    return x > 0.0f ? x : 0.0f;
}

/* ------------------------------------------------------------------ */
/* Pre-emphasis filter: y[n] = x[n] - 0.97 * x[n-1]
 * Matches Silero VAD PyTorch training. samples[0] is left unchanged
 * (assumes x[-1] = 0). */
static void pre_emphasize(float *samples, int n) {
    if (n <= 1) return;
    /* Process in reverse; skip samples[0] (it has no predecessor) */
    for (int i = n - 1; i > 0; i--) {
        samples[i] = samples[i] - 0.97f * samples[i - 1];
    }
}

/* Downsample 48kHz -> 16kHz with 3-tap averaging anti-alias filter.
 * Moving average acts as a crude low-pass to reduce aliasing
 * of frequencies above 8kHz when decimating by 3. */
static void downsample_48k_to_16k(const float *in, float *out, int in_len) {
    int out_len = in_len / 3;
    for (int i = 0; i < out_len && i < VAD_FRAME_SIZE; i++) {
        int idx = i * 3;
        float a = (idx < in_len) ? in[idx] : 0.0f;
        float b = (idx + 1 < in_len) ? in[idx + 1] : 0.0f;
        float c = (idx + 2 < in_len) ? in[idx + 2] : 0.0f;
        out[i] = (a + b + c) / 3.0f;
    }
}

/* ------------------------------------------------------------------ */
/* Conv1D forward pass
 *   input:  [1][in_len]  (in_len = VAD_FRAME_SIZE = 512)
 *   output: [CONV_OUT_CH][out_len]
 *   out_len = (in_len - CONV_KERNEL) / CONV_STRIDE + 1 = 2
 */
#define CONV_OUT_LEN ((VAD_FRAME_SIZE - CONV_KERNEL) / CONV_STRIDE + 1)

static void conv1d_forward(const float *input,
                           const float *weight,
                           const float *bias,
                           float *output) {
    for (int c = 0; c < CONV_OUT_CH; c++) {
        for (int t = 0; t < CONV_OUT_LEN; t++) {
            float sum = bias ? bias[c] : 0.0f;
            for (int k = 0; k < CONV_KERNEL; k++) {
                int in_idx = t * CONV_STRIDE + k;
                if (in_idx < VAD_FRAME_SIZE) {
                    sum += input[in_idx] * weight[c * CONV_KERNEL + k];
                }
            }
            output[c * CONV_OUT_LEN + t] = relu(sum);
        }
    }
}

/* ------------------------------------------------------------------ */
/* GRU cell: single step
 *   x: [GRU_INPUT_SIZE]   input at current time step
 *   h: [GRU_HIDDEN_SIZE]  hidden state (in-place updated)
 *
 * Gates: r = reset, z = update, n = new
 */
static void gru_step(const float *x, float *h) {
    float r[GRU_HIDDEN_SIZE];
    float z[GRU_HIDDEN_SIZE];
    float n[GRU_HIDDEN_SIZE];

    const float *w_ih = gru_w_ih;
    const float *w_hh = gru_w_hh;
    const float *b_ih = gru_b_ih;
    const float *b_hh = gru_b_hh;

    for (int i = 0; i < GRU_HIDDEN_SIZE; i++) {
        /* Reset gate: r = sigmoid(W_ir @ x + b_ir + W_hr @ h + b_hr) */
        float r_sum = b_ih ? b_ih[i] : 0.0f;
        r_sum += b_hh ? b_hh[i] : 0.0f;
        for (int j = 0; j < GRU_INPUT_SIZE; j++) {
            r_sum += w_ih[i * GRU_INPUT_SIZE + j] * x[j];
        }
        for (int j = 0; j < GRU_HIDDEN_SIZE; j++) {
            r_sum += w_hh[i * GRU_HIDDEN_SIZE + j] * h[j];
        }
        r[i] = sigmoid(r_sum);

        /* Update gate: z = sigmoid(W_iz @ x + b_iz + W_hz @ h + b_hz) */
        float z_sum = b_ih ? b_ih[GRU_HIDDEN_SIZE + i] : 0.0f;
        z_sum += b_hh ? b_hh[GRU_HIDDEN_SIZE + i] : 0.0f;
        for (int j = 0; j < GRU_INPUT_SIZE; j++) {
            z_sum += w_ih[(GRU_HIDDEN_SIZE + i) * GRU_INPUT_SIZE + j] * x[j];
        }
        for (int j = 0; j < GRU_HIDDEN_SIZE; j++) {
            z_sum += w_hh[(GRU_HIDDEN_SIZE + i) * GRU_HIDDEN_SIZE + j] * h[j];
        }
        z[i] = sigmoid(z_sum);

        /* New gate: n = tanh(W_in @ x + b_in + r * (W_hn @ h + b_hn)) */
        float n_sum = b_ih ? b_ih[2 * GRU_HIDDEN_SIZE + i] : 0.0f;
        n_sum += b_hh ? b_hh[2 * GRU_HIDDEN_SIZE + i] : 0.0f;
        for (int j = 0; j < GRU_INPUT_SIZE; j++) {
            n_sum += w_ih[(2 * GRU_HIDDEN_SIZE + i) * GRU_INPUT_SIZE + j] * x[j];
        }
        float hn_sum = 0.0f;
        for (int j = 0; j < GRU_HIDDEN_SIZE; j++) {
            hn_sum += w_hh[(2 * GRU_HIDDEN_SIZE + i) * GRU_HIDDEN_SIZE + j] * h[j];
        }
        n[i] = tanhf(n_sum + r[i] * hn_sum);
    }

    /* Update hidden state: h_new = (1 - z) * n + z * h */
    for (int i = 0; i < GRU_HIDDEN_SIZE; i++) {
        h[i] = (1.0f - z[i]) * n[i] + z[i] * h[i];
    }
}

/* ------------------------------------------------------------------ */
/* FC + Sigmoid: input [64] -> output [1] probability */
static float fc_sigmoid(const float *input) {
    float sum = fc_bias ? fc_bias[0] : 0.0f;
    for (int i = 0; i < GRU_HIDDEN_SIZE; i++) {
        sum += fc_weight[i] * input[i];
    }
    return sigmoid(sum);
}

/* ------------------------------------------------------------------ */
/* Public API */

void vad_init(int model_ptr, int sample_rate) {
    sr = (sample_rate == 48000) ? 48000 : 16000;
    memset(hidden_state, 0, sizeof(hidden_state));

#ifdef VAD_LOAD_WEIGHTS_AT_RUNTIME
    if (model_ptr != 0) {
        float *base = (float *)model_ptr;
        int offset = 0;
        conv_weight = base + offset; offset += 64 * 256;
        conv_bias   = base + offset; offset += 64;
        gru_w_ih    = base + offset; offset += 192 * 64;
        gru_w_hh    = base + offset; offset += 192 * 64;
        gru_b_ih    = base + offset; offset += 192;
        gru_b_hh    = base + offset; offset += 192;
        fc_weight   = base + offset; offset += 64;
        fc_bias     = base + offset; offset += 1;
    }
#else
    (void)model_ptr;
    conv_weight = weights_conv_weight;
    conv_bias   = weights_conv_bias;
    gru_w_ih    = weights_gru_w_ih;
    gru_w_hh    = weights_gru_w_hh;
    gru_b_ih    = weights_gru_b_ih;
    gru_b_hh    = weights_gru_b_hh;
    fc_weight   = weights_fc_weight;
    fc_bias     = weights_fc_bias;
#endif
}

float vad_process(int input_ptr, int samples) {
    const float *input_48k = (const float *)input_ptr;
    float frame_16k[VAD_FRAME_SIZE];
    float conv_output[CONV_OUT_CH * CONV_OUT_LEN];
    float gru_input[GRU_INPUT_SIZE];

    /* Step 1: Downsample 48kHz -> 16kHz */
    int src_samples = (samples > 0) ? samples : VAD_INPUT_48K_SIZE;
    if (sr == 48000) {
        downsample_48k_to_16k(input_48k, frame_16k, src_samples);
    } else {
        int n = (src_samples < VAD_FRAME_SIZE) ? src_samples : VAD_FRAME_SIZE;
        memcpy(frame_16k, input_48k, n * sizeof(float));
        if (n < VAD_FRAME_SIZE) {
            memset(frame_16k + n, 0, (VAD_FRAME_SIZE - n) * sizeof(float));
        }
    }

    /* Step 2: Pre-emphasis (must match PyTorch training) */
    pre_emphasize(frame_16k, VAD_FRAME_SIZE);

    /* Step 3: Conv1D feature extraction */
    conv1d_forward(frame_16k, conv_weight, conv_bias, conv_output);

    /* Step 4: GRU - process each time step */
    for (int t = 0; t < CONV_OUT_LEN; t++) {
        for (int c = 0; c < CONV_OUT_CH; c++) {
            gru_input[c] = conv_output[c * CONV_OUT_LEN + t];
        }
        gru_step(gru_input, hidden_state);
    }

    /* Step 5: FC + Sigmoid */
    return fc_sigmoid(hidden_state);
}

void vad_reset(void) {
    memset(hidden_state, 0, sizeof(hidden_state));
}
