/*
 * weights.h — Silero VAD model weights (auto-generated by extract_weights.py)
 * DO NOT EDIT — generated from silero_vad.onnx
 * Generated on 2026-07-23T18:37:34.626789
 */

#ifndef SILERO_VAD_WEIGHTS_H
#define SILERO_VAD_WEIGHTS_H

/*
 * Model architecture:
 *   Conv1D(1, 64, kernel=256, stride=160)
 *   GRU(64, 64, 1)
 *   FC(64, 1) + Sigmoid
 */

/* --- Conv1D weight & bias --- */
/* shape: [64, 1, 256] = 0 floats */
static const float weights_conv_weight[0] = {
    /* MISSING */
};

/* shape: [64] = 0 floats */
static const float weights_conv_bias[0] = {
    /* MISSING */
};

/* --- GRU weights --- */
/* GRU has 3 gates (reset, update, new), each with input and hidden projections */
/* shape: [3 * 64, 64] = 0 floats */
static const float weights_gru_w_ih[0] = {
    /* MISSING */
};

/* shape: [3 * 64, 64] = 0 floats */
static const float weights_gru_w_hh[0] = {
    /* MISSING */
};

/* shape: [3 * 64] = 0 floats */
static const float weights_gru_b_ih[0] = {
    /* MISSING */
};

/* shape: [3 * 64] = 0 floats */
static const float weights_gru_b_hh[0] = {
    /* MISSING */
};

/* --- Fully connected weight & bias --- */
/* shape: [1, 64] = 0 floats */
static const float weights_fc_weight[0] = {
    /* MISSING */
};

/* shape: [1] = 0 floats */
static const float weights_fc_bias[0] = {
    /* MISSING */
};

#endif /* SILERO_VAD_WEIGHTS_H */
